// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *aboutme → timeline*
 */
export interface AboutmeDocumentDataTimelineItem {
  /**
   * title field in *aboutme → timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o ano da timeline
   * - **API ID Path**: aboutme.timeline[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *aboutme → timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a descrição
   * - **API ID Path**: aboutme.timeline[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *aboutme → contacts*
 */
export interface AboutmeDocumentDataContactsItem {
  /**
   * email field in *aboutme → contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite seu email
   * - **API ID Path**: aboutme.contacts[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * linkedin field in *aboutme → contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Digite seu linkedin
   * - **API ID Path**: aboutme.contacts[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * github field in *aboutme → contacts*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Digite seu github
   * - **API ID Path**: aboutme.contacts[].github
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;
}

/**
 * Content for aboutme documents
 */
interface AboutmeDocumentData {
  /**
   * name field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite seu nome
   * - **API ID Path**: aboutme.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * office field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite sua profissão
   * - **API ID Path**: aboutme.office
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  office: prismic.KeyTextField;

  /**
   * description field in *aboutme*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a sua descrição
   * - **API ID Path**: aboutme.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * avatar field in *aboutme*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * resume field in *aboutme*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://drive.curriculo.com
   * - **API ID Path**: aboutme.resume
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  resume: prismic.LinkField;

  /**
   * timeline field in *aboutme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.timeline[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  timeline: prismic.GroupField<Simplify<AboutmeDocumentDataTimelineItem>>;

  /**
   * contacts field in *aboutme*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contacts: prismic.GroupField<Simplify<AboutmeDocumentDataContactsItem>>;
}

/**
 * aboutme document from Prismic
 *
 * - **API ID**: `aboutme`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutmeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutmeDocumentData>,
    "aboutme",
    Lang
  >;

/**
 * Item in *Aplicativos → Dados do app na Apple Store*
 */
export interface AplicativosDocumentDataDataAppleStoreItem {
  /**
   * Rating field in *Aplicativos → Dados do app na Apple Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a  nota geral
   * - **API ID Path**: aplicativos.data_apple_store[].rating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rating: prismic.KeyTextField;

  /**
   * Number Rating field in *Aplicativos → Dados do app na Apple Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o número de avaliações
   * - **API ID Path**: aplicativos.data_apple_store[].number_rating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_rating: prismic.KeyTextField;

  /**
   * Number Downloads field in *Aplicativos → Dados do app na Apple Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o número de downloads
   * - **API ID Path**: aplicativos.data_apple_store[].number_downloads
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_downloads: prismic.KeyTextField;
}

/**
 * Item in *Aplicativos → Dados do app na Play Store*
 */
export interface AplicativosDocumentDataDataPlayStoreItem {
  /**
   * Rating field in *Aplicativos → Dados do app na Play Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a  nota geral
   * - **API ID Path**: aplicativos.data_play_store[].rating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rating: prismic.KeyTextField;

  /**
   * Number Rating field in *Aplicativos → Dados do app na Play Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o número de avaliações
   * - **API ID Path**: aplicativos.data_play_store[].number_rating
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_rating: prismic.KeyTextField;

  /**
   * Number Downloads field in *Aplicativos → Dados do app na Play Store*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o número de downloads
   * - **API ID Path**: aplicativos.data_play_store[].number_downloads
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_downloads: prismic.KeyTextField;
}

/**
 * Item in *Aplicativos → Technologies*
 */
export interface AplicativosDocumentDataTechnologiesItem {
  /**
   * Name field in *Aplicativos → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a tecnologia
   * - **API ID Path**: aplicativos.technologies[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Aplicativos → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o link da feature
   * - **API ID Path**: aplicativos.technologies[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Aplicativos → Screenshots*
 */
export interface AplicativosDocumentDataScreenshotsItem {
  /**
   * Image Url field in *Aplicativos → Screenshots*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o link das screenshots
   * - **API ID Path**: aplicativos.screenshots[].image_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_url: prismic.KeyTextField;
}

/**
 * Content for Aplicativos documents
 */
interface AplicativosDocumentData {
  /**
   * Nome field in *Aplicativos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o nome do aplicativo
   * - **API ID Path**: aplicativos.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Logo Grande field in *Aplicativos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.logo_large
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_large: prismic.ImageField<never>;

  /**
   * Logo Pequeno field in *Aplicativos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.logo_small
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_small: prismic.ImageField<never>;

  /**
   * Description field in *Aplicativos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a descrição
   * - **API ID Path**: aplicativos.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Status field in *Aplicativos*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Ativo
   * - **API ID Path**: aplicativos.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"Ativo" | "Desativado", "filled">;

  /**
   * Apple Store field in *Aplicativos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Digite o link do aplicativo na Apple Store
   * - **API ID Path**: aplicativos.apple_store
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  apple_store: prismic.LinkField;

  /**
   * Play Store field in *Aplicativos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Digite o link do aplicativo na Play Store
   * - **API ID Path**: aplicativos.play_store
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  play_store: prismic.LinkField;

  /**
   * Dados do app na Apple Store field in *Aplicativos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.data_apple_store[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data_apple_store: prismic.GroupField<
    Simplify<AplicativosDocumentDataDataAppleStoreItem>
  >;

  /**
   * Dados do app na Play Store field in *Aplicativos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.data_play_store[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data_play_store: prismic.GroupField<
    Simplify<AplicativosDocumentDataDataPlayStoreItem>
  >;

  /**
   * Technologies field in *Aplicativos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  technologies: prismic.GroupField<
    Simplify<AplicativosDocumentDataTechnologiesItem>
  >;

  /**
   * Screenshots field in *Aplicativos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: aplicativos.screenshots[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  screenshots: prismic.GroupField<
    Simplify<AplicativosDocumentDataScreenshotsItem>
  >;
}

/**
 * Aplicativos document from Prismic
 *
 * - **API ID**: `aplicativos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AplicativosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AplicativosDocumentData>,
    "aplicativos",
    Lang
  >;

/**
 * Item in *Websites → Technologies*
 */
export interface WebsitesDocumentDataTechnologiesItem {
  /**
   * Nome field in *Websites → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o nome da feature
   * - **API ID Path**: websites.technologies[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Websites → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o link da feature
   * - **API ID Path**: websites.technologies[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Websites → Screenshots*
 */
export interface WebsitesDocumentDataScreenshotsItem {
  /**
   * Imagem URL field in *Websites → Screenshots*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.screenshots[].image_url
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_url: prismic.ImageField<never>;
}

/**
 * Content for Websites documents
 */
interface WebsitesDocumentData {
  /**
   * Posição do projeto field in *Websites*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Digite o numero da posição do projeto
   * - **API ID Path**: websites.order_value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order_value: prismic.NumberField;

  /**
   * Nome field in *Websites*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o nome do projeto
   * - **API ID Path**: websites.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Status field in *Websites*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Concluído
   * - **API ID Path**: websites.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"Concluído" | "Em desenvolvimento", "filled">;

  /**
   * Imagem URL field in *Websites*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.image_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_url: prismic.ImageField<never>;

  /**
   * Repositorio field in *Websites*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite o link do repositorio
   * - **API ID Path**: websites.repository_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  repository_url: prismic.KeyTextField;

  /**
   * Website field in *Websites*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Digite a URL do website
   * - **API ID Path**: websites.preview_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  preview_url: prismic.LinkField;

  /**
   * Description field in *Websites*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digite a descrição do projeto
   * - **API ID Path**: websites.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Technologies field in *Websites*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  technologies: prismic.GroupField<
    Simplify<WebsitesDocumentDataTechnologiesItem>
  >;

  /**
   * Screenshots field in *Websites*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: websites.screenshots[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  screenshots: prismic.GroupField<
    Simplify<WebsitesDocumentDataScreenshotsItem>
  >;
}

/**
 * Websites document from Prismic
 *
 * - **API ID**: `websites`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsitesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WebsitesDocumentData>,
    "websites",
    Lang
  >;

export type AllDocumentTypes =
  | AboutmeDocument
  | AplicativosDocument
  | WebsitesDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutmeDocument,
      AboutmeDocumentData,
      AboutmeDocumentDataTimelineItem,
      AboutmeDocumentDataContactsItem,
      AplicativosDocument,
      AplicativosDocumentData,
      AplicativosDocumentDataDataAppleStoreItem,
      AplicativosDocumentDataDataPlayStoreItem,
      AplicativosDocumentDataTechnologiesItem,
      AplicativosDocumentDataScreenshotsItem,
      WebsitesDocument,
      WebsitesDocumentData,
      WebsitesDocumentDataTechnologiesItem,
      WebsitesDocumentDataScreenshotsItem,
      AllDocumentTypes,
    };
  }
}
