import { Metadata } from 'next'
import Image from 'next/image'
import { useProfile } from '@/hooks/useProfile'
import { Navigation } from '@/components/Navigation'
import { AboutMe } from '@/components/AboutMe'
import { MyServices } from '@/components/MyServices'
import { SoftwaresOnline } from '@/components/SoftwaresOnline'
import { Repositories } from '@/components/Repositories'
import { Footer } from '@/components/Footer'
import { ProjectModal } from '@/components/ProjectModal'
import { Contributions } from '@/components/Contributions'
import { ProjectModalApp } from '@/components/ProjectModalApp'

import waves from '@/assets/images/waves.svg'
import styles from '@/styles/Home.module.scss'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <Navigation />
      <main className={styles.main_container}>
        <section id="start" className={styles.front_cover}>
          <div className={styles.presentation}>
            <div>
              <h1>Desenvolvedor</h1>
            </div>
            <div>
              <h1>Frontend.</h1>
            </div>
            <p>
              Ajudando empresas e pessoas a criar aplicações digitais de forma
              moderna e de alta qualidade.
            </p>
          </div>

          <Image className={styles.waves} src={waves} alt="waves" />
        </section>

        <AboutMe />
        <MyServices />
        <Contributions />
        <Repositories />
        <SoftwaresOnline />
        <Footer />

        <ProjectModal />
        <ProjectModalApp />
      </main>
    </>
  )
}
